// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_bmht_observed_bicor
arma::mat cpp_bmht_observed_bicor(NumericMatrix expr);
RcppExport SEXP _bicorX_cpp_bmht_observed_bicor(SEXP exprSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type expr(exprSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bmht_observed_bicor(expr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bmht_permutations
NumericMatrix cpp_bmht_permutations(NumericMatrix expr, IntegerMatrix shuffled_conds, double half_threshold, double mad_1, double mad_2, int threads);
RcppExport SEXP _bicorX_cpp_bmht_permutations(SEXP exprSEXP, SEXP shuffled_condsSEXP, SEXP half_thresholdSEXP, SEXP mad_1SEXP, SEXP mad_2SEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type shuffled_conds(shuffled_condsSEXP);
    Rcpp::traits::input_parameter< double >::type half_threshold(half_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type mad_1(mad_1SEXP);
    Rcpp::traits::input_parameter< double >::type mad_2(mad_2SEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bmht_permutations(expr, shuffled_conds, half_threshold, mad_1, mad_2, threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fast_bicor_matrix
NumericMatrix cpp_fast_bicor_matrix(NumericMatrix expr, int threads);
RcppExport SEXP _bicorX_cpp_fast_bicor_matrix(SEXP exprSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fast_bicor_matrix(expr, threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bmkc_adjacency
List cpp_bmkc_adjacency(NumericMatrix cor1, NumericMatrix cor2, double T1, double T2, bool unsigned_net, bool is_percentile, int threads);
RcppExport SEXP _bicorX_cpp_bmkc_adjacency(SEXP cor1SEXP, SEXP cor2SEXP, SEXP T1SEXP, SEXP T2SEXP, SEXP unsigned_netSEXP, SEXP is_percentileSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cor1(cor1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cor2(cor2SEXP);
    Rcpp::traits::input_parameter< double >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< double >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< bool >::type unsigned_net(unsigned_netSEXP);
    Rcpp::traits::input_parameter< bool >::type is_percentile(is_percentileSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bmkc_adjacency(cor1, cor2, T1, T2, unsigned_net, is_percentile, threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rosdet_observed_bicor
arma::mat cpp_rosdet_observed_bicor(NumericMatrix expr);
RcppExport SEXP _bicorX_cpp_rosdet_observed_bicor(SEXP exprSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type expr(exprSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rosdet_observed_bicor(expr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rosdet_bootstrap_batch
IntegerVector cpp_rosdet_bootstrap_batch(NumericMatrix expr_sub, IntegerVector g1_mapped, IntegerVector g2_mapped, NumericVector obs_distance, NumericVector c_weights, IntegerMatrix shuffled_labels, int threads);
RcppExport SEXP _bicorX_cpp_rosdet_bootstrap_batch(SEXP expr_subSEXP, SEXP g1_mappedSEXP, SEXP g2_mappedSEXP, SEXP obs_distanceSEXP, SEXP c_weightsSEXP, SEXP shuffled_labelsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type expr_sub(expr_subSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g1_mapped(g1_mappedSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g2_mapped(g2_mappedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs_distance(obs_distanceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c_weights(c_weightsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type shuffled_labels(shuffled_labelsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rosdet_bootstrap_batch(expr_sub, g1_mapped, g2_mapped, obs_distance, c_weights, shuffled_labels, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bicorX_cpp_bmht_observed_bicor", (DL_FUNC) &_bicorX_cpp_bmht_observed_bicor, 1},
    {"_bicorX_cpp_bmht_permutations", (DL_FUNC) &_bicorX_cpp_bmht_permutations, 6},
    {"_bicorX_cpp_fast_bicor_matrix", (DL_FUNC) &_bicorX_cpp_fast_bicor_matrix, 2},
    {"_bicorX_cpp_bmkc_adjacency", (DL_FUNC) &_bicorX_cpp_bmkc_adjacency, 7},
    {"_bicorX_cpp_rosdet_observed_bicor", (DL_FUNC) &_bicorX_cpp_rosdet_observed_bicor, 1},
    {"_bicorX_cpp_rosdet_bootstrap_batch", (DL_FUNC) &_bicorX_cpp_rosdet_bootstrap_batch, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_bicorX(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
