#' @importFrom igraph graph_from_adjacency_matrix max_cliques E plot.igraph layout_in_circle
#' @importFrom ggplot2 ggplot aes geom_tile scale_fill_gradient labs theme_minimal
NULL

# -----------------------------------------------------------------------------
# Main BMKC Function
# -----------------------------------------------------------------------------

#' Run the BMKC analysis to find differentially coexpressed gene modules.
#'
#' Implements the BMKC (Biweight Midcorrelation and k-Clique) method.
#' This method identifies modules of genes that are highly coexpressed in one
#' condition but not the other.
#'
#' @param expr_matrix A numeric matrix where rows are genes and columns are samples.
#' @param condition A factor or character vector with two levels, matching the columns of `expr_matrix`.
#' @param T1 The absolute correlation threshold for the first condition.
#' @param T2 The absolute correlation threshold for the second condition.
#' @param min_clique_size The minimum number of genes for a clique to be reported.
#' @param workers An integer specifying the number of parallel workers to use for correlation calculation. Defaults to 1.
#' @return A list containing the identified gene modules and parameters.
#' @export
run_bmkc <- function(expr_matrix, condition, T1 = 0.7, T2 = 0.3, min_clique_size = 4, workers = 1) {

  # --- Input Validation ---
  conditions <- unique(condition)
  if (length(conditions) != 2) stop("Condition vector must have exactly two levels.")

  cond1 <- conditions[1]; cond2 <- conditions[2]

  # Calculate bicor matrices for both conditions using the parallel helper
  cor_1 <- compute_cor_matrix(expr_matrix[, condition == cond1], workers = workers)
  cor_2 <- compute_cor_matrix(expr_matrix[, condition == cond2], workers = workers)

  # "Differential Coexpression Threshold" strategy
  adj_matrix <- (abs(cor_1) >= T1) & (abs(cor_2) <= T2)

  adj_matrix <- apply(adj_matrix, 2, as.numeric)
  rownames(adj_matrix) <- colnames(adj_matrix)

  # Use igraph to find maximal cliques
  graph <- igraph::graph_from_adjacency_matrix(adj_matrix, mode = "undirected", diag = FALSE)
  cliques <- igraph::max_cliques(graph, min = min_clique_size)

  gene_modules <- lapply(cliques, function(clique) {
    names(clique)
  })

  # Return a standard list object
  output <- list(
    modules = gene_modules,
    parameters = list(T1 = T1, T2 = T2, min_clique_size = min_clique_size),
    data = list(
      expr_matrix = expr_matrix,
      condition = condition
    )
  )

  return(output)
}

# -----------------------------------------------------------------------------
# Helper function for threshold exploration (IMPROVED VERSION)
# -----------------------------------------------------------------------------

#' Explore parameter space for BMKC analysis.
#'
#' This function helps users choose optimal T1 and T2 thresholds by testing a
#' grid of values and reporting the number of modules found for each combination.
#'
#' @param expr_matrix A numeric matrix where rows are genes and columns are samples.
#' @param condition A factor or character vector with two levels.
#' @param T1_range A numeric vector of T1 thresholds to test.
#' @param T2_range A numeric vector of T2 thresholds to test.
#' @param min_clique_size The minimum clique size to use for the test.
#' @param workers An integer specifying the number of parallel workers to use. Defaults to 1.
#' @return A data frame containing the exploration results, ready for plotting.
#' @export
explore_bmkc_thresholds <- function(expr_matrix, condition,
                                    T1_range = seq(0.5, 0.9, by = 0.1),
                                    T2_range = seq(0.1, 0.5, by = 0.1),
                                    min_clique_size = 4,
                                    workers = 1) {

  message("Exploring thresholds... This may take a moment.")

  # Create a grid of all parameter combinations
  param_grid <- expand.grid(T1 = T1_range, T2 = T2_range)

  # This helper function will be run for each row of the parameter grid
  run_single_bmkc_test <- function(t1, t2) {
    tryCatch({
      result <- run_bmkc(expr_matrix, condition, T1 = t1, T2 = t2, min_clique_size = min_clique_size, workers = workers)
      if (is.list(result) && "modules" %in% names(result)) {
        return(length(result$modules))
      }
      return(0)
    }, error = function(e) {
      warning(paste("An error occurred at T1=", t1, ", T2=", t2, ". Details:", e$message))
      return(0)
    })
  }

  # Calculate number of modules for each combination
  param_grid$n_modules <- mapply(run_single_bmkc_test, param_grid$T1, param_grid$T2)

  return(param_grid)
}

#' Plot the results of a BMKC threshold exploration.
#'
#' Generates a heatmap visualizing the number of modules found for different
#' combinations of T1 and T2 thresholds.
#'
#' @param exploration_result A data frame generated by `explore_bmkc_thresholds`.
#' @return A ggplot2 object.
#' @export
plot_bmkc_exploration <- function(exploration_result) {
  p <- ggplot2::ggplot(exploration_result, ggplot2::aes(x = T1, y = T2, fill = n_modules)) +
    ggplot2::geom_tile(color = "white") +
    ggplot2::scale_fill_gradient(low = "lightblue", high = "darkblue", name = "Number of\nModules") +
    ggplot2::labs(
      title = "BMKC Threshold Exploration",
      subtitle = paste("Number of modules found at different T1 and T2 thresholds"),
      x = "Threshold for High Correlation (T1)",
      y = "Threshold for Low Correlation (T2)"
    ) +
    ggplot2::theme_minimal()
  return(p)
}

