# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_bmht_observed_bicor <- function(expr) {
    .Call(`_bicorX_cpp_bmht_observed_bicor`, expr)
}

cpp_bmht_permutations <- function(expr, shuffled_conds, half_threshold, mad_1, mad_2, threads) {
    .Call(`_bicorX_cpp_bmht_permutations`, expr, shuffled_conds, half_threshold, mad_1, mad_2, threads)
}

cpp_fast_bicor_matrix <- function(expr, threads) {
    .Call(`_bicorX_cpp_fast_bicor_matrix`, expr, threads)
}

cpp_bmkc_adjacency <- function(cor1, cor2, T1, T2, unsigned_net, is_percentile, threads) {
    .Call(`_bicorX_cpp_bmkc_adjacency`, cor1, cor2, T1, T2, unsigned_net, is_percentile, threads)
}

cpp_rosdet_observed_bicor <- function(expr) {
    .Call(`_bicorX_cpp_rosdet_observed_bicor`, expr)
}

cpp_rosdet_bootstrap_batch <- function(expr_sub, g1_mapped, g2_mapped, obs_distance, c_weights, shuffled_labels, threads) {
    .Call(`_bicorX_cpp_rosdet_bootstrap_batch`, expr_sub, g1_mapped, g2_mapped, obs_distance, c_weights, shuffled_labels, threads)
}

